before:
  hooks:
  - go mod download
builds:
- id: kubectl-grep
  main: ./cmd/kubectl-grep
  binary: kubectl-grep
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: windows
    goarch: arm64
